export const GRANDFATHERED_KEY = "GRANDFATHERED";
export const GRANDFATHERED_VALUE = "true";
export const ZUORA_SYNC_SKIP_UPDATE_KEY = "ZUORA__SYNC_SKIP_UPDATE";
export const ZUORA_DISCOUNT_PERCENTAGE_KEY = "ZUORA__DISCOUNT_PERCENTAGE";
